# Generated by Django 4.1.7 on 2023-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_full_name_customers_adders_customers_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='contact_signed_date',
        ),
        migrations.AddField(
            model_name='customers',
            name='contract_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
