# Generated by Django 4.1.7 on 2023-03-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customers_contact_signed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='interconnection_approved',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_approved',
            field=models.BooleanField(),
        ),
    ]
