# Generated by Django 4.1.7 on 2023-03-02 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_alter_customers_interconnection_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customersfiles',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersfiles',
            name='field',
            field=models.CharField(choices=[('utility_and_esid', 'Utility & ESID'), ('approved_permit', 'Approved Permit'), ('contract', 'Contract'), ('stamped_plans', 'Stamped Plans'), ('ub', 'UB'), ('hoi', 'HOI'), ('front_of_house', 'Front Of House'), ('panel_layout', 'Panel Layout'), ('post_install_letter', 'Post Install Letter')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersfiles',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customersfiles',
            name='uploaded_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='adders',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ahj',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ahj_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='bank_funded',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='battery',
            field=models.CharField(choices=[('no_bat', 'No Battery'), ('3_kw', '3KW'), ('6_kw', '6KW'), ('10_kw', '10KW')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='commission_percentage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contract_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='design_requested',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='dob',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='equipment_ordered',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='finance_company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='install_complete',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='install_confirmed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='install_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='interconnection_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='interconnection_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='number_of_panels',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='paid_to_closer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='paid_to_manager',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='paid_to_setter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pe_stamp_requested',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_plan_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='previous_company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='project_cost',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='sold_with',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ss',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='their_company_cost',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='their_company_mo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='utility_and_esid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
