# Generated by Django 4.1.7 on 2023-03-03 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_customersfiles_customersattachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customersattachments',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='customersattachments',
            name='attachment',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customersattachments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
