# Generated by Django 4.1.7 on 2023-03-03 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0008_customerspeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='closer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='user_closer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='user_manager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='setter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='user_setter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
