# Generated by Django 4.1.7 on 2023-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customers_closer_alter_customers_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='design_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pe_stamp_requested',
            field=models.BooleanField(default=False),
        ),
    ]
