# Generated by Django 4.1.7 on 2023-03-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customers_design_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='design_fee',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
