# Generated by Django 4.1.7 on 2023-03-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_rename_nsold_with_customers_sold_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='battery_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='design_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='design_requested_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='equipment_ordered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_ordered_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='install_complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='install_complete_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='install_confirmed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='install_confirmed_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='interconnection_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ic_approved_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='interconnection_submitted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ic_submitted_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pe_stamp_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pe_stamp_requested_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='permit_approved_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_submitted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='permit_submitted_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='sold_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sold_with_options', to='customers.customerselectoptions'),
        ),
    ]
