# Generated by Django 4.1.7 on 2023-03-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_customers_battery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='interconnection_approved',
            new_name='ic_approved',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='interconnection_submitted',
            new_name='ic_submitted',
        ),
    ]
