# Generated by Django 4.1.7 on 2023-03-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_rename_interconnection_approved_customers_ic_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='bank_funded',
            new_name='calc_red',
        ),
    ]
