# Generated by Django 4.1.7 on 2023-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_rename_bank_funded_customers_calc_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='bank_funded',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
