# Generated by Django 4.1.7 on 2023-03-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_customers_bank_funded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='bank_funded',
            new_name='bank_fundeds',
        ),
    ]
