# Generated by Django 4.1.7 on 2023-03-06 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0024_rename_bank_fundeds_customers_bank_funded'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUpdates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=255)),
                ('from_value', models.CharField(max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
