# Generated by Django 4.1.7 on 2023-03-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_rename_customerupdates_customeractivitylogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivitylogs',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='customers.customers'),
            preserve_default=False,
        ),
    ]
