# Generated by Django 4.1.7 on 2023-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_customeractivitylogs_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivitylogs',
            name='field_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
