# Generated by Django 4.1.7 on 2023-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_customeractivitylogs_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='approved_permit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
