# Generated by Django 4.1.7 on 2023-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_alter_customers_approved_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='approved_permit',
        ),
        migrations.AlterField(
            model_name='customersattachments',
            name='field',
            field=models.CharField(choices=[('approved_permit', 'Approved Permit'), ('contract', 'Contract'), ('stamped_plans', 'Stamped Plans'), ('ub', 'UB'), ('hoi', 'HOI'), ('front_of_house', 'Front Of House'), ('panel_layout', 'Panel Layout'), ('post_install_letter', 'Post Install Letter')], max_length=255),
        ),
    ]
