# Generated by Django 4.1.7 on 2023-03-12 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0030_remove_customers_approved_permit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='battery_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='design_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='design_requested_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='equipment_ordered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_ordered_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ic_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ic_approved_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ic_submitted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ic_submitted_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='install_complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='install_complete_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='install_confirmed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='install_confirmed_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pe_stamp_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pe_stamp_requested_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permit_approved_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='permit_submitted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permit_submitted_options', to='customers.customerselectoptions'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='sold_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_with_options', to='customers.customerselectoptions'),
        ),
        migrations.CreateModel(
            name='CustomerGroups',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customergroups'),
        ),
    ]
