# Generated by Django 4.1.7 on 2023-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_alter_customers_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerselectoptions',
            name='color',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
