# Generated by Django 4.1.7 on 2023-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0032_customerselectoptions_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerselectoptions',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
