# Generated by Django 4.1.7 on 2023-03-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0033_alter_customerselectoptions_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='sold_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sold_with_options', to='customers.customerselectoptions'),
        ),
    ]
